version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "16:00"
  open-pull-requests-limit: 15
  reviewers:
    - jwcook
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "16:00"
  open-pull-requests-limit: 5
  reviewers:
    - jwcook
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
